# Generated by Django 6.0.5 on 2026-06-02 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("path", models.CharField(db_index=True, max_length=255)),
                ("section", models.CharField(blank=True, db_index=True, max_length=64)),
                ("method", models.CharField(default="GET", max_length=8)),
                ("status_code", models.PositiveSmallIntegerField(default=200)),
                ("response_ms", models.PositiveIntegerField(default=0)),
                ("is_authenticated", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("hour", models.PositiveSmallIntegerField(default=0)),
                ("weekday", models.PositiveSmallIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="page_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp", "section"],
                        name="analytics_p_timesta_0d73da_idx",
                    ),
                    models.Index(
                        fields=["section", "timestamp"],
                        name="analytics_p_section_0fdb77_idx",
                    ),
                ],
            },
        ),
    ]
