# Generated by Django 6.0.5 on 2026-06-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visitor_key",
                    models.CharField(db_index=True, max_length=80, unique=True),
                ),
                ("features", models.JSONField(default=dict)),
                ("recency_days", models.PositiveIntegerField(default=0)),
                ("window_days", models.PositiveSmallIntegerField(default=30)),
                ("computed_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "ordering": ["-computed_at"],
            },
        ),
    ]
