# Generated by Django 6.0.5 on 2026-06-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_visitorfeatures"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageview",
            name="dwell_ms",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pageview",
            name="view_token",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
