# Generated by Django 6.0.5 on 2026-06-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_experiment_experimentassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnomalyAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric", models.CharField(default="daily_traffic", max_length=40)),
                ("date", models.DateField()),
                ("value", models.FloatField()),
                ("z_score", models.FloatField()),
                ("direction", models.CharField(max_length=8)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("metric", "date")},
            },
        ),
    ]
