# Generated by Django 6.0.7 on 2026-07-18 21:08

import django.db.models.functions.text
from django.db import migrations, models


def normalize_and_validate_emails(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    seen = set()
    for user in CustomUser.objects.exclude(email='').order_by('pk').iterator():
        normalized = user.email.strip().lower()
        if normalized in seen:
            raise RuntimeError(
                'Case-insensitive duplicate user emails must be resolved before this migration.'
            )
        seen.add(normalized)
        if user.email != normalized:
            CustomUser.objects.filter(pk=user.pk).update(email=normalized)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_customuser_phone_number_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(normalize_and_validate_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower('email'),
                condition=models.Q(('email', ''), _negated=True),
                name='unique_customuser_email_ci',
            ),
        ),
    ]
