# Generated by Django 6.0.5 on 2026-05-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreminder',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentreminder',
            name='notify_via_sms',
            field=models.BooleanField(default=False),
        ),
    ]
