# Generated by Django 6.0.7 on 2026-07-18 21:14

from django.db import migrations, models


def copy_legacy_delivery_timestamps(apps, schema_editor):
    PaymentReminder = apps.get_model('debt_management', 'PaymentReminder')
    PaymentReminder.objects.filter(
        notify_via_email=True,
        last_notified_at__isnull=False,
    ).update(email_last_notified_at=models.F('last_notified_at'))
    PaymentReminder.objects.filter(
        notify_via_sms=True,
        last_notified_at__isnull=False,
    ).update(sms_last_notified_at=models.F('last_notified_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('debt_management', '0002_paymentreminder_last_notified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreminder',
            name='email_last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentreminder',
            name='sms_last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(copy_legacy_delivery_timestamps, migrations.RunPython.noop),
    ]
