# Generated by Django 6.0.5 on 2026-05-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="uses_paper_trading",
            field=models.BooleanField(
                default=False,
                help_text="Rank players by live paper-trading portfolio value instead of mini-game bonuses.",
            ),
        ),
    ]
