# Generated by Django 6.0.5 on 2026-05-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_integration', '0002_plaiditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaiditem',
            name='access_token',
            field=models.CharField(help_text='Encrypted; use get_access_token() / set_access_token() instead of touching this directly.', max_length=512),
        ),
    ]
