# Generated by Django 6.0.5 on 2026-05-30 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_integration", "0003_alter_plaiditem_access_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerageLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("snaptrade", "SnapTrade")],
                        default="snaptrade",
                        max_length=20,
                    ),
                ),
                ("provider_user_id", models.CharField(blank=True, max_length=128)),
                (
                    "user_secret",
                    models.CharField(
                        blank=True,
                        help_text="Encrypted; use get_user_secret() / set_user_secret() rather than reading directly.",
                        max_length=512,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brokerage_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "provider")},
            },
        ),
    ]
