# Generated by Django 6.0.7 on 2026-07-18 21:08

from django.conf import settings
from django.db import migrations, models


def collapse_provider_duplicates(apps, schema_editor):
    Account = apps.get_model('data_integration', 'Account')
    Transaction = apps.get_model('data_integration', 'Transaction')
    Investment = apps.get_model('data_integration', 'Investment')
    Debt = apps.get_model('data_integration', 'Debt')

    account_groups = (
        Account.objects.exclude(external_id='')
        .values('user_id', 'external_id')
        .annotate(row_count=models.Count('pk'))
        .filter(row_count__gt=1)
    )
    for group in account_groups.iterator():
        accounts = Account.objects.filter(
            user_id=group['user_id'],
            external_id=group['external_id'],
        ).order_by('-updated_at', '-pk')
        keeper = accounts.first()
        duplicate_ids = list(accounts.exclude(pk=keeper.pk).values_list('pk', flat=True))
        Transaction.objects.filter(account_id__in=duplicate_ids).update(account_id=keeper.pk)
        Investment.objects.filter(account_id__in=duplicate_ids).update(account_id=keeper.pk)
        Debt.objects.filter(account_id__in=duplicate_ids).update(account_id=keeper.pk)
        Account.objects.filter(pk__in=duplicate_ids).delete()

    transaction_groups = (
        Transaction.objects.exclude(external_id='')
        .values('account_id', 'external_id')
        .annotate(row_count=models.Count('pk'))
        .filter(row_count__gt=1)
    )
    for group in transaction_groups.iterator():
        transactions = Transaction.objects.filter(
            account_id=group['account_id'],
            external_id=group['external_id'],
        ).order_by('-updated_at', '-pk')
        keeper = transactions.first()
        transactions.exclude(pk=keeper.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('data_integration', '0003_alter_plaiditem_access_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(collapse_provider_duplicates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(
                condition=models.Q(('external_id', ''), _negated=True),
                fields=('user', 'external_id'),
                name='unique_account_external_id_per_user',
            ),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(
                condition=models.Q(('external_id', ''), _negated=True),
                fields=('account', 'external_id'),
                name='unique_transaction_external_id_per_account',
            ),
        ),
    ]
